services:
  db:
    image: postgres:15-alpine
    container_name: postgres_aset_it
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: db_manajemen_aset
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build:
      context: ./Dashboard Aset Management IT
      dockerfile: Dockerfile
    container_name: web_aset_it
    restart: always
    ports:
      - "3005:3000"
    depends_on:
      - db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_aset_it
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_PASS=${DB_PASS}
    depends_on:
      - db

volumes:
  pgdata:
